-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, SUM(O.SALES_AMOUNT * P.PRICE) AS SALES
FROM PRODUCT P RIGHT OUTER JOIN OFFLINE_SALE O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;


# (SELECT P.PRODUCT_CODE AS PRODUCT_CODE, COUNT(O.SALES_AMOUNT) AS COUNT
# FROM PRODUCT P INNER JOIN OFFLINE_SALE O
# ON P.PRODUCT_ID = O.PRODUCT_ID
# GROUP BY P.PRODUCT_CODE) Z
# GROUP BY Z.PRODUCT_CODE 
# ORDER BY SALES DESC;